# site settings
title: Yves Stadler 
subtitle: Doctor of Philosophy in Information Technology
email: yves.stadler@gmail.com
description: Design by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://mvy.github.io" # the base hostname & protocol for your site
author: Yves `M'vy` Stadler
street_address: 
city: 
state: 
zip_code: 
country: France
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/yvesstadler
pinterest_url:
slack_url:
twitter_url: https://twitter.com/mvyonline

# build settings
markdown: kramdown

sass:
  style: compressed
